spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9093,localhost:9094
          zk-nodes: localhost
      bindings:
        netshoesProducts:
          group: testando